### ISSUE TITLE
我有什么办法能让chatbot做出准确的回答？

### ISSUE THREAD

**Issue by qiuyuyang910** [Dimsmary/Ossas_ChatBot#11]

**Comment by Dimsmary** [comment]
可以具体描述你的问题吗？

**Comment by qiuyuyang910** [comment]
在很多时候，我用训练过的问题原封不动问chatbot，但是它不能正确的回答，这个主要是哪方面的问题？

**Comment by Dimsmary** [comment]
一般accurancy达到80以上才开始比较贴合训练数据。

**Comment by qiuyuyang910** [comment]
为啥我的accurancy从未超过1？

**Comment by Dimsmary** [comment]
不好意思，我的意思是80% 也就是0.8

**Comment by qiuyuyang910** [comment]
那我的accurancy已经超过90%但是在某些问题上即使用训练的问题也不能正确的回答

**Comment by Linear1024** [comment]
训练的数据越多accurancy越低是什么情况呢

**Comment by Redroadsl** [comment]
> 
> 
> 训练的数据越多accurancy越低是什么情况呢

海越大，针越难捞

**Comment by heckerpowered** [comment]
循环轮数和batch size应该设置为多少才能让机器人的回复像个人样
