### ISSUE TITLE
一些疑惑，希望能得到解答

### ISSUE THREAD

**Issue by Onining** [Dimsmary/Ossas_ChatBot#13]
1.闪退的问题，不知道是怎么回事下载的文件一直缺斤少两
详情：缺少标签文件"words_dictionary.txt"
2.CQHTTP，发送监听HTTP请求时报错，尝试自行修订，未果
详情：[HTTP] http上报地址 127.0.0.1:7777 无法访问

**Comment by Dimsmary** [comment]
1）请先进行训练后再进行问答。
2）如果QQ消息的接收和发送没有问题，则该报错可忽略。

**Comment by Onining** [comment]
写个Q&A
A：
1）训练之后，能够正常对话（嘴臭）
2）自己研究了一下应该是服务器只能接受get请求，post请求无法处理，所以会报错。但是不会影响我们使用，数据流已经上传可被ossas接受并处理。
Q：
1）发现模型容易出现过拟合，不能很好的展现对话（嘴臭）效果
预想修改方向：
1.数据集需要修改；
2.玄学调参

**Comment by Onining** [comment]
PLUS
A：
1）用“1，2.1，2”的形式打标签效果会比“1，2，2，2.1，2，2，”的形式好。用后面这种，会出现反馈语句混乱的情况。
