### ISSUE TITLE
python包版本号能否提供下？

### ISSUE THREAD

**Issue by tricyzhou** [Dimsmary/Ossas_ChatBot#2]
python包版本号能否提供下？

**Comment by Dimsmary** [comment]
python使用的是3.7 但更新的版本我想也应该可以适用

**Comment by tricyzhou** [comment]
sry我可能没表述清楚 我想知道一下requirements.txt里面的包的版本号  求告知

**Comment by Dimsmary** [comment]
tensorflow == 2.1.0
pandas == 1.0.3
xlrd == 1.2.0
jieba == 0.42.1
numpy == 1.18.2
requirements已更新
