### ISSUE TITLE
一些建议和疑惑

### ISSUE THREAD

**Issue by charleszhao999** [Dimsmary/Ossas_ChatBot#3]
首先是聊天记录的分类太繁琐了，希望能够增加：自动为“你”的消息标记标签2
并自动为“你”的消息前一条非“你”的消息标记1
这样想必能相更快地标记信息

其次是我使用cuda来训练模型时，每次都会跳出这样的提示，并且程序自动关闭。希望能解答一下是否出了什么差错
![image](https://user-images.githubusercontent.com/63227229/78540671-18010880-7827-11ea-9982-964f686a502d.png)
![image](https://user-images.githubusercontent.com/63227229/78540685-1cc5bc80-7827-11ea-9355-71a08ff63369.png)
![image](https://user-images.githubusercontent.com/63227229/78540692-20594380-7827-11ea-8c46-9f6d3ee62d3a.png)

**Comment by charleszhao999** [comment]
另外也希望作者能告知一下建议的循环次数以及batch size

**Comment by Dimsmary** [comment]
这看起来应该是内存不足导致的错误，建议使用小一点的batch_size。
具体循环次数和batch_size需要摸索，我也不是非常确定。
当accurancy到达80左右时，可以进行对话判断拟合情况，如果效果不佳可以尝试继续训练。
您的建议我会在后续版本中考虑添加。
