### ISSUE TITLE
从开启之后窗口无输出然后自动关闭

### ISSUE THREAD

**Issue by Xintakazi** [Dimsmary/Ossas_ChatBot#4]
安装了vc++

**Comment by Dimsmary** [comment]
使用控制台运行，再看下有没输出，如果有则上传截图。

**Comment by Xintakazi** [comment]
无效

**Comment by Dimsmary** [comment]
可以具体描述吗？控制台运行是否仍然自动退出？

**Comment by Xintakazi** [comment]
如果不是我理解错的话，我用cmd开启软件，过一会
![image](https://user-images.githubusercontent.com/50211095/78703021-18d78e80-793c-11ea-8c81-38ef5eb2e24a.png)
![image](https://user-images.githubusercontent.com/50211095/78703233-69e78280-793c-11ea-81fd-ff4993a00a4f.png)
显示如上

**Comment by Dimsmary** [comment]
你的电脑是否安装python？是否安装了VC++？

**Comment by Xintakazi** [comment]
确认安装
![image](https://user-images.githubusercontent.com/50211095/78760258-7824b580-79b3-11ea-9f8e-d5ce4b3cced8.png)
![image](https://user-images.githubusercontent.com/50211095/78760306-8a9eef00-79b3-11ea-8f07-9ba74dea6d6c.png)

**Comment by Dimsmary** [comment]
看起来有点奇怪的是，打包在exe内的python解释器似乎调用到了本地python环境的库。
有三个解决方案：
1）卸载python
2）pip仅安装tensorflow后，尝试再次运行exe
3）pip安装requirements.txt内所有依赖库，直接运行main.py

**Comment by Dimsmary** [comment]
经过多人反馈，这个问题似乎是计算机与tensorflow兼容性所导致的。
https://www.tensorflow.org/install/errors给出了解决方案。
此issue的问题已超出了项目，故close
