### ISSUE TITLE
一个建议和一个兼容问题

### ISSUE THREAD

**Issue by fhghb-czy** [Dimsmary/Ossas_ChatBot#6]
请问您可以多做一个不是单exe的版本发出来吗？
这样大家就都可以使用里面的库文件放到.py版本的目录里面测试了。
感觉.exe文件的版本支持不是很好。我Win10x86的电脑不知道为什么刚点开exe就提示不兼容此电脑。

**Comment by Dimsmary** [comment]
依赖库可以直接通过requirements.txt安装。安装完成后可以直接运行main.py
exe打包是直接使用pyinstaller打包的 兼容性也确实不太好。
