### ISSUE TITLE
关于生僻词词典的一些困惑

### ISSUE THREAD

**Issue by qiuyuyang910** [Dimsmary/Ossas_ChatBot#9]
问一下这个有什么用，虽然说是辅助程序但想问一下如果不向里面添加词和添加了词的区别以及对相同训练数据所训练出来的有什么影响

**Comment by Dimsmary** [comment]
可以参看 https://github.com/fxsjy/jieba [主要功能>载入词典] 部分

**Comment by Dimsmary** [comment]
没有添加生僻词的训练可能会将生僻词拆开，会导致语义偏差。

**Comment by qiuyuyang910** [comment]
谢谢解答，我还想问一下train_data文件夹下的words_dictionary.txt是干什么用的

**Comment by Dimsmary** [comment]
用于词向量和文本词语的转换，记录了每个词向量对应的词语。
